"use strict";
const $ = id => document.getElementById(id);
const token = document.querySelector('meta[name="console-token"]').content;
const state = {catalog:null, registry:null, selections:[], batchOffset:0, batchNext:null,
  selected:new Map(), publications:new Map(), publicationNext:null, queryGeneration:0, receiving:false, publishing:false, batchGeneration:0, detailGeneration:0, catalogGeneration:0};
const statuses = {validated:"核对通过", quarantined:"待核对"};
const reasons = {reported_value:"原报表区间值",complete_daily_source_values:"逐日完整数据合计",duplicate_daily_records:"逐日来源记录重复",missing_reported_value:"原报表未提供",missing_dates:"日期未覆盖完整",
  missing_metric_values:"部分记录缺少指标",aggregation_not_registered:"保留各来源记录，未登记区间合计",
  aggregation_scope_unreviewed:"时区或筛选条件待核对",aggregation_requires_daily_source_records:"来源不是完整逐日记录",
  ranked_records_only:"按来源窗口保留榜单",no_contained_source_records:"没有完整落在区间内的记录",
  ambiguous_source_scope_or_window:"来源范围或窗口存在冲突"};
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(className)n.className=className;return n;}
function showStatus(id,text,error=false){const n=$(id);n.textContent=text;n.className="status"+(error?" error":"");}
function exact(value){return value===null||value===undefined?"未提供":typeof value==="object"?JSON.stringify(value,null,2):String(value);}
function jsonDetail(parent,label,data){const d=el("details"),s=el("summary",label);d.append(s,el("pre",JSON.stringify(data,null,2)));parent.append(d);}
function table(headers,rows){const wrap=el("div",undefined,"table-scroll"),t=el("table"),head=el("tr");headers.forEach(x=>head.append(el("th",x)));const thead=el("thead");thead.append(head);t.append(thead);const body=el("tbody");rows.forEach(row=>{const tr=el("tr");row.forEach(value=>{const cell=el("td");cell.append(value instanceof Node?value:document.createTextNode(exact(value)));tr.append(cell);});body.append(tr);});t.append(body);wrap.append(t);return wrap;}
async function request(path,body){const options={headers:{"X-Console-Token":token},cache:"no-store"};if(body!==undefined){options.method="POST";options.headers["Content-Type"]="application/json";options.body=JSON.stringify(body);}const response=await fetch(path,options);const text=await response.text();let value;try{value=JSON.parse(text);}catch{throw new Error(text||"服务未返回结果。");}if(!response.ok){throw new Error(typeof value.detail==="string"?value.detail:JSON.stringify(value.detail||value));}if(value.number_encoding!=="decimal_text")throw new Error("展示格式不匹配，请刷新页面。");return value.data;}
function active(panel){document.querySelectorAll(".panel").forEach(n=>n.hidden=n.id!==panel+"-panel");document.querySelectorAll("nav button").forEach(n=>{n.classList.toggle("active",n.dataset.panel===panel);n.setAttribute("aria-pressed",String(n.dataset.panel===panel));});}
document.querySelectorAll("nav button").forEach(n=>n.addEventListener("click",()=>active(n.dataset.panel)));
function selectedSource(){return state.selections.find(x=>JSON.stringify([x.kind,x.selection_id])===$("selection").value);}
function intakeEnabled(){["selection","source-file","revision","refresh-registry"].forEach(id=>$(id).disabled=state.receiving);$("predecessors").querySelectorAll("input").forEach(n=>n.disabled=state.receiving);$("receive").disabled=state.receiving||!selectedSource()||!$("source-file").files.length;}
function sourceChanged(){const source=selectedSource();$("receipts").replaceChildren();$("predecessors").replaceChildren();$("receive-result").replaceChildren();showStatus("receive-status","");if(!source){$("receipts").textContent="尚无所选来源。";intakeEnabled();return;}source.receipts.forEach(r=>{const section=el("div",undefined,"receipt");section.append(el("h4",r.store_id+" 店 · "+r.period_start+" — "+r.period_end),el("p",r.dataset_id,"muted"));section.append(el("p","来源页面："+r.source_page,"muted"),el("p","格式："+r.mapping_version+" · 提取时间："+r.extracted_at,"muted"));if(r.source_block_line)section.append(el("p","原文门店行："+r.source_block_line,"muted"));section.append(el("code","文件 SHA256："+r.file_sha256));jsonDetail(section,"查看独立登记",r);$("receipts").append(section);const label=el("label",r.upload_id+" 的前序批次 ID"),input=el("input");input.dataset.upload=r.upload_id;input.placeholder="batch_…（仅已有同范围数据时填写）";label.append(input);$("predecessors").append(label);});intakeEnabled();}
$("selection").addEventListener("change",sourceChanged);
$("revision").addEventListener("change",()=>$("predecessors").hidden=!$("revision").checked);
$("source-file").addEventListener("change",()=>{const f=$("source-file").files[0];$("file-status").textContent=f?f.name+" · "+f.size+" 字节":"请选择原文件。";intakeEnabled();});
async function refreshCatalog(){if(state.receiving)return;const generation=++state.catalogGeneration;try{const c=await request("/console/catalog");if(generation!==state.catalogGeneration||state.receiving)return;state.catalog=c;state.registry=c.registry;state.selections=c.registry?c.registry.selections:[];const prior=$("selection").value;$("selection").replaceChildren(new Option("请选择已登记来源",""));state.selections.forEach(s=>$("selection").append(new Option(s.selection_id+" · "+s.receipts.length+" 个数据组",JSON.stringify([s.kind,s.selection_id]))));if([...$("selection").options].some(o=>o.value===prior))$("selection").value=prior;const previous=$("dataset").value;$("dataset").replaceChildren();c.datasets.forEach(d=>$("dataset").append(new Option(d.dataset_id,d.dataset_id)));if(previous)$("dataset").value=previous;else $("dataset").value="store_period_panel_metrics";datasetChanged();sourceChanged();showStatus("global-status",Object.keys(c.issues).length?Object.entries(c.issues).map(([k,v])=>k+"："+v).join("；"):state.selections.length?"已读取独立登记。上传数据与查询分别操作。":"尚无已核对的上传登记。请先配置真实来源，再刷新登记。");}catch(e){showStatus("global-status",e.message,true);}}
$("refresh-registry").addEventListener("click",refreshCatalog);
function encodedBytes(buffer){const bytes=new Uint8Array(buffer);let text="";for(let i=0;i<bytes.length;i+=16384)text+=String.fromCharCode(...bytes.subarray(i,i+16384));return btoa(text);}
$("receive").addEventListener("click",async()=>{const s=selectedSource(),f=$("source-file").files[0];if(!s||!f)return;if(!f.size||f.size>8*1024*1024){showStatus("receive-status","请选择非空且不超过 8 MiB 的原文件。",true);return;}const expected=state.registry.registry_sha256;const supersedes={};if($("revision").checked)$("predecessors").querySelectorAll("input").forEach(n=>{if(n.value.trim())supersedes[n.dataset.upload]=n.value.trim();});state.receiving=true;state.catalogGeneration++;intakeEnabled();showStatus("receive-status","正在核对整份文件并留存…");try{const result=await request("/console/receive",{kind:s.kind,selection_id:s.selection_id,registry_sha256:expected,source_base64:encodedBytes(await f.arrayBuffer()),supersedes});showStatus("receive-status",result.idempotent?"文件已接收，返回原批次。":statuses[result.status]||result.status,result.status!=="validated");const panel=$("receive-result");panel.replaceChildren();const card=el("div",undefined,"card");card.append(el("h3","接收结果 · "+s.selection_id+" · "+f.name));result.errors.forEach(e=>card.append(el("p",e,"error")));const ids=[...result.batches.map(b=>b.batch_id)];if(result.quarantine_batch_id)ids.push(result.quarantine_batch_id);ids.forEach(id=>{const b=el("button","查看 "+id,"secondary");b.addEventListener("click",()=>{active("batches");loadDetail(id);});card.append(b);});jsonDetail(card,"完整接收结果",result);panel.append(card);state.batchOffset=0;await refreshBatches();}catch(e){showStatus("receive-status",e.message,true);}finally{state.receiving=false;intakeEnabled();}});
function updateSelected(){$("selection-count").textContent=state.selected.size?"已选 "+state.selected.size+" 个批次":"未选择批次";$("publish").disabled=state.publishing||!state.selected.size;$("selected-batches").replaceChildren(table(["批次 ID","门店与窗口","数据分类"],[...state.selected.values()].map(b=>[b.batch_id,b.context.store_id+" · "+b.context.period_start+" — "+b.context.period_end,b.context.dataset_id])));}
async function refreshBatches(){const generation=++state.batchGeneration;try{const data=await request("/console/batches?offset="+state.batchOffset);if(generation!==state.batchGeneration)return;state.batchNext=data.next_offset;updateSelected();$("batch-list").replaceChildren();if(!data.items.length)$("batch-list").append(el("p","尚未接收数据。","empty"));else $("batch-list").append(table(["选择","接收时间 / 提取时间","门店与报表窗口","分类 / 上传标识","核对结果","详情"],data.items.map(b=>{const box=el("input");box.type="checkbox";box.disabled=b.status!=="validated";box.checked=state.selected.has(b.batch_id);box.setAttribute("aria-label","选择批次 "+b.batch_id);box.addEventListener("change",()=>{box.checked?state.selected.set(b.batch_id,b):state.selected.delete(b.batch_id);updateSelected();});const info=b.context;const detail=el("button","查看");detail.addEventListener("click",()=>loadDetail(b.batch_id));return [box,b.received_at+"\n提取："+exact(b.extracted_at),info?info.store_id+" · "+info.period_start+" — "+info.period_end:"归属待核对",(info?info.dataset_id+"\n":"")+b.upload_id,el("span",statuses[b.status]||b.status,"badge"+(b.status==="quarantined"?" held":"")),detail];})));$("batch-prev").disabled=state.batchOffset===0;$("batch-next").disabled=data.next_offset===null;}catch(e){if(generation!==state.batchGeneration)return;$("batch-list").replaceChildren(el("p",e.message,"error"));}};
$("clear-selection").addEventListener("click",()=>{state.selected.clear();refreshBatches();});
$("refresh-batches").addEventListener("click",()=>{state.batchOffset=0;refreshBatches();});$("batch-prev").addEventListener("click",()=>{state.batchOffset=Math.max(0,state.batchOffset-50);refreshBatches();});$("batch-next").addEventListener("click",()=>{if(state.batchNext!==null){state.batchOffset=Number(state.batchNext);refreshBatches();}});
async function loadDetail(id){const generation=++state.detailGeneration;try{const b=await request("/console/batches/"+encodeURIComponent(id));if(generation!==state.detailGeneration)return;const target=$("batch-detail");target.replaceChildren();const card=el("div",undefined,"card");card.append(el("h3",statuses[b.status]+" · "+b.batch_id));if(b.supersedes_batch_id)card.append(el("p","修订前序："+b.supersedes_batch_id,"muted"));b.errors.forEach(x=>card.append(el("p",x,"error")));if(b.preview){(b.preview.errors||[]).forEach(x=>card.append(el("p",x,"error")));(b.preview.quarantined_records||[]).forEach(r=>{card.append(el("h4","待核对来源行 "+r.source_line_end));(r.errors||[]).forEach(x=>card.append(el("p",x,"error")));jsonDetail(card,"该行原值",r.source_record||r);});const rows=b.preview.validated_records||[];renderRecords(card,rows.map(r=>({record:r.record,source:{source_line_end:r.source_line_end,...(r.source_locator?{source_locator:r.source_locator}:{})}})),b.status==="validated"?"核对通过的记录":"解析候选记录（批次待核对）");}jsonDetail(card,"校验结果与原登记",b);target.append(card);target.scrollIntoView({block:"nearest"});}catch(e){if(generation!==state.detailGeneration)return;$("batch-detail").replaceChildren(el("p",e.message,"error"));}}
$("publish").addEventListener("click",async()=>{const ids=[...state.selected.keys()];if(!ids.length)return;state.publishing=true;updateSelected();showStatus("publish-status","正在重放所选来源并发布…");try{const m=await request("/console/publish",{batch_ids:ids});showStatus("publish-status","发布完成。所选批次已固定为一个版本。");$("publish-result").replaceChildren(el("p","已发布 "+m.batch_ids.length+" 个批次 · "+m.summary.record_count+" 条来源记录"),el("pre",m.publication_id));const use=el("button","用此版本查询","secondary");use.addEventListener("click",async()=>{active("query");await refreshPublications(false,m);$("publication").value=m.publication_id;invalidateQuery();queryEnabled();});$("publish-result").append(use);jsonDetail($("publish-result"),"查看本版所选批次",m);}catch(e){showStatus("publish-status",e.message,true);}finally{state.publishing=false;updateSelected();}});
async function refreshPublications(more=false,created=null){try{if(!more){state.publications.clear();state.publicationNext=null;}const data=await request("/console/publications?offset="+(more?state.publicationNext:0));data.items.forEach(x=>state.publications.set(x.publication_id,x));if(created)state.publications.set(created.publication_id,{...created,available:true});state.publicationNext=data.next_offset;const previous=$("publication").value;$("publication").replaceChildren(new Option("请选择一个明确版本",""));state.publications.forEach(p=>{const o=new Option(p.publication_id+(p.available?"":" · 未通过当前查询校验"),p.publication_id);o.disabled=!p.available;$("publication").append(o);});if(state.publications.get(previous)?.available)$("publication").value=previous;$("publication-more").disabled=data.next_offset===null;$("publication-status").textContent=data.items.length?"只读取明确选择的版本。 "+[...state.publications.values()].filter(p=>!p.available).map(p=>p.publication_id+"："+p.message).join("；"):"尚无发布版本，请先选择批次发布。";invalidateQuery();queryEnabled();}catch(e){$("publication-status").textContent=e.message;}}
$("refresh-publications").addEventListener("click",()=>refreshPublications());$("publication-more").addEventListener("click",()=>refreshPublications(true));
function invalidateQuery(){state.queryGeneration++;$("query-result").replaceChildren();showStatus("query-status","");}
function datasetChanged(){const d=state.catalog?.datasets.find(x=>x.dataset_id===$("dataset").value);$("fields").replaceChildren();if(d)d.fields.forEach(f=>$("fields").append(new Option(f.label+" · "+f.name,f.name)));queryEnabled();invalidateQuery();}
function storeIDs(){return $("stores").value.split(/[,，]/).map(s=>s.trim()).filter(Boolean);}
function queryEnabled(){const selected=!!$("publication").value;const stores=storeIDs();const grain=state.catalog?.datasets.find(x=>x.dataset_id===$("dataset").value)?.grain;const reviewable=grain==="store_period";$("query").disabled=!selected;$("review").disabled=!selected||!reviewable;$("baseline-enabled").disabled=!reviewable||stores.length!==1;if($("baseline-enabled").disabled)$("baseline-enabled").checked=false;$("baseline-controls").hidden=!$("baseline-enabled").checked;$("review-note").textContent=!reviewable?"榜单按来源窗口查看原记录。RAC 使用店铺期间指标。":stores.length>1?"多店使用同一所选区间；同店比较可另选较早基准区间。":"RAC 根据本次证据重新核对观察、假设与判断。";}
$("dataset").addEventListener("change",datasetChanged);$("window-mode").addEventListener("change",()=>{const month=$("window-mode").value==="month";$("month-control").hidden=!month;$("start-control").hidden=month;$("end-control").hidden=month;});
["publication","stores","window-mode","month","start","end","fields","baseline-enabled","baseline-start","baseline-end"].forEach(id=>$(id).addEventListener("input",()=>{invalidateQuery();queryEnabled();}));
function queryBody(review){const p={publication_id:$("publication").value,dataset_id:$("dataset").value,store_ids:storeIDs()};if(!p.store_ids.length)throw new Error("请填写明确的门店标识。");if($("window-mode").value==="month"){if(!$("month").value)throw new Error("请选择月份。");p.month=$("month").value;}else{p.period_start=$("start").value;p.period_end=$("end").value;if(!p.period_start||!p.period_end)throw new Error("请选择完整首尾日期。");}const fields=[...$("fields").selectedOptions].map(o=>o.value);if(fields.length)p.fields=fields;if(review&&$("baseline-enabled").checked)p.baseline={period_start:$("baseline-start").value,period_end:$("baseline-end").value};return p;}
function fieldLabel(name){const d=state.catalog?.datasets.find(x=>x.dataset_id===$("dataset").value);return d?.fields.find(f=>f.name===name)?.label||name;}
function renderSource(parent,source){if(source.source_locator){const l=source.source_locator;const spans=[{fields:["门店"],span:l.store},{fields:["日期"],span:l.window},...l.values];const d=el("details");d.append(el("summary","原文片段"+(l.item_ordinal?" · 榜单第 "+l.item_ordinal+" 项":"")));d.append(table(["字段","行 / 列","原文"],spans.map(v=>[v.fields.join("、"),v.span.line+" / "+v.span.column_start+"—"+v.span.column_end+"（末列不含）",v.span.text])));parent.append(d);}jsonDetail(parent,"完整来源定位",source);}
function renderRAC(parent,rac){const status={supported:"有证据支持",contradicted:"与证据不符",unresolved:"待核对"};parent.append(el("h3","检查与差值"),table(["字段","本次检查","结果","差值"],rac.checks.map(c=>[fieldLabel(c.field),c.claim,status[c.status]||c.status,c.difference===null||c.difference===undefined?"—":c.difference+(c.field.endsWith("_pct")?" 个百分点":"")])));const h=el("details");h.append(el("summary","竞争假设"),table(["假设","核对结果","证据 ID"],rac.hypotheses.map(x=>[x.claim,status[x.status]||x.status,x.evidence_ids.join("、")])));parent.append(h);if(rac.critic_findings.length){parent.append(el("h3","仍需核对的条件"));rac.critic_findings.forEach(x=>parent.append(el("p",x.issue)));}}
function renderRecords(parent,records,title){if(!records.length)return;const detail=el("details");detail.append(el("summary",title+" · "+records.length+" 条"));records.slice(0,200).forEach(item=>{const r=item.record,section=el("div",undefined,"receipt");section.append(el("h4",r.store_id+" · "+r.period_start+" — "+r.period_end));section.append(table(["字段","原值"],Object.entries(r).filter(([k])=>!["store_id","period_start","period_end"].includes(k)).map(([k,v])=>[fieldLabel(k)+" · "+k,exact(v)])));renderSource(section,item.source);detail.append(section);});if(records.length>200)detail.append(el("p","此处展示前 200 条，完整数据见下方完整结果。","muted"));parent.append(detail);}
function renderQuery(parent,q){parent.append(el("p","版本："+q.publication_id,"muted"),el("p",q.period_start+" — "+q.period_end+" · "+q.dataset_id,"muted"));q.stores.forEach(store=>{const card=el("div",undefined,"card");card.append(el("h3",store.store_id+" 店"),el("p","日期覆盖："+store.coverage.covered_days+" / "+store.coverage.requested_days+" 天","muted"));card.append(table(["字段","区间值","依据","缺值记录数"],Object.entries(store.metrics).map(([k,m])=>[fieldLabel(k),m.value===null?"暂无可用区间值":exact(m.value),reasons[m.reason]||m.reason||m.basis,m.coverage.null_source_records])));if(store.coverage.missing_ranges.length)jsonDetail(card,"未覆盖的日期",store.coverage.missing_ranges);renderRecords(card,store.records,"原始窗口记录");renderRecords(card,store.overlapping_records,"与查询区间部分重叠的记录");parent.append(card);});}
async function runQuery(review){let body;try{body=queryBody(review);}catch(e){showStatus("query-status",e.message,true);return;}const generation=++state.queryGeneration;$("query-result").replaceChildren();$("query").disabled=true;$("review").disabled=true;showStatus("query-status",review?"正在按所选证据运行 RAC…":"正在读取所选版本…");try{const result=await request(review?"/console/review":"/console/query",body);if(generation!==state.queryGeneration)return;const target=$("query-result");if(review){const card=el("div",undefined,"card");card.append(el("h3","RAC 本次核对"),el("div",typeof result.rac.final_report==="string"?result.rac.final_report:JSON.stringify(result.rac.final_report,null,2),"report"));renderRAC(card,result.rac);["checks","hypotheses","critic_findings","belief_update","evidence_packets"].forEach((key,i)=>jsonDetail(card,["检查与差值","竞争假设","仍需核对的条件","本轮判断更新","证据与原文来源"][i],result.rac[key]));target.append(card);renderQuery(target,result.query);if(result.baseline){const base=el("details");base.append(el("summary","基准区间证据"));renderQuery(base,result.baseline);target.append(base);}}else renderQuery(target,result);jsonDetail(target,"完整结果（数值按原精度显示）",result);showStatus("query-status","已读取固定版本；本次查询未保存。");}catch(e){if(generation===state.queryGeneration)showStatus("query-status",e.message,true);}finally{if(generation===state.queryGeneration)queryEnabled();}}
$("query").addEventListener("click",()=>runQuery(false));$("review").addEventListener("click",()=>runQuery(true));
refreshCatalog();refreshBatches();refreshPublications();
